name: TourneyUtils
version: '${project.version}'
main: dev.cross.tourneyutils.Tourneyutils
api-version: 1.19
authors: [ Cross ]
description: Made to give a better experience in events.
commands:
  remove:
    usage: /remove
    description: Removes the player from every team.
  add:
    usage: /add
    description: Adds a player to a team.
  list:
    usage: /list
    description: Lists all the player on a team.
  announce:
    usage: /announce
    description: Announces the next round.
  allteleport:
    usage: /allteleport
    description: Teleports all players from a specific team to your current location.
  countdown:
    usage: /countdown
    description: Counts down.
  setlocation:
    usage: /setlocation
    description: Saves your current location to be used in the /allteleport command.
  party:
    usage: /party
    description: Activates the party chat
  mute:
    usage: /mute
    description: Mutes chat.