package dev.cross.tourneyutils.manager

enum class Teams {
    LAVENDER_LIGHTERS, YELLOW_YAKS, ORANGE_OCELOTS, LIME_LLAMAS, PINK_PARROTS, PURPLE_PANDAS, BLUE_BATS, RED_RABBITS, GREEN_GECKOS, CYAN_COYOTES, AQUA_AXOLOTLS, NONE
}